vich_uploader:
    db_driver: orm

    mappings:
       images_aliments:
           uri_prefix: /images/aliments
           upload_destination: '%kernel.project_dir%/public/images/aliments'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
       images_types:
           uri_prefix: /images/types
           upload_destination: '%kernel.project_dir%/public/images/types'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
